// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC788qzNuYntiTnX_6y_QSjYmGNEurZYU0',
    appId: '1:116157365880:web:3f217bf3dad8808183b78d',
    messagingSenderId: '116157365880',
    projectId: 'newflutterdb',
    authDomain: 'newflutterdb.firebaseapp.com',
    storageBucket: 'newflutterdb.appspot.com',
    measurementId: 'G-8ZQYH5CGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAge9MO8IfHWWcFghVX7YlOJnwY3uuL2Ts',
    appId: '1:116157365880:android:51fc5b1265c737f983b78d',
    messagingSenderId: '116157365880',
    projectId: 'newflutterdb',
    storageBucket: 'newflutterdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSXDxtb4Sw4hlF5R9tL07eWPryPiiXpY',
    appId: '1:116157365880:ios:dae8fbb4dc3a4dc883b78d',
    messagingSenderId: '116157365880',
    projectId: 'newflutterdb',
    storageBucket: 'newflutterdb.appspot.com',
    iosBundleId: 'com.example.firebaseClyde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSXDxtb4Sw4hlF5R9tL07eWPryPiiXpY',
    appId: '1:116157365880:ios:faa322b1dc12af4e83b78d',
    messagingSenderId: '116157365880',
    projectId: 'newflutterdb',
    storageBucket: 'newflutterdb.appspot.com',
    iosBundleId: 'com.example.firebaseClyde.RunnerTests',
  );
}
